/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.NhanVienDao;
import entity.NhanVien;
import java.io.File;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import url.RmiConfig;

/**
 *
 * @author TriHieu
 */
public class Gui_Mail extends javax.swing.JPanel {

    private String duongDan;
    private boolean isMultipleRecipients = false;
//    private NhanVienImpl nVDAO = new NhanVienImpl();
    private NhanVienDao nvDAO;

    private static final String URL = RmiConfig.RMI_URL;
    List<NhanVien> NhanvienList = nvDAO.docTuBang();

    public Gui_Mail() throws java.rmi.RemoteException {
        try {
            nvDAO = (NhanVienDao) Naming.lookup(URL + "NhanVien");
        } catch (RemoteException | MalformedURLException | NotBoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtEmailto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDuongDan = new javax.swing.JTextField();
        btnHuyChonF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        radioNTK = new javax.swing.JRadioButton();
        radio1TK = new javax.swing.JRadioButton();
        btnChonFDinhKem1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.jpg"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setText("hoductrihieu@gmail.com");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 16, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 58, -1, 18));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Email Send:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 20, -1, 18));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setText("cfeh zhly akov yune");
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 54, 210, -1));

        txtEmailto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtEmailto, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 98, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email To:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 102, -1, 18));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Subject");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 150, -1, 18));

        txtSubject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 142, 210, -1));

        txtMessage.setColumns(20);
        txtMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 174, 375, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Message");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 223, -1, 18));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Chọn File Đính Kèm");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 323, -1, 18));

        txtDuongDan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtDuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 319, 266, -1));

        btnHuyChonF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuyChonF.setText("Hủy Chọn");
        btnHuyChonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyChonFActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuyChonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 363, -1, 26));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Gửi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 483, 102, -1));

        radioNTK.setText("Gửi tất cả email nhân viên");
        radioNTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNTKActionPerformed(evt);
            }
        });
        jPanel1.add(radioNTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        radio1TK.setText("Gửi 1 tài khoản");
        radio1TK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1TKActionPerformed(evt);
            }
        });
        jPanel1.add(radio1TK, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 433, -1, -1));

        btnChonFDinhKem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChonFDinhKem1.setText("Chọn File");
        btnChonFDinhKem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFDinhKem1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnChonFDinhKem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 363, -1, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Thông Báo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(451, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(477, 477, 477))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 881, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyChonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyChonFActionPerformed
        duongDan = null;
        txtDuongDan.setText("");
    }//GEN-LAST:event_btnHuyChonFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<String> arrayEmail = new ArrayList<String>();

        if (isMultipleRecipients == true) {
            for (NhanVien nV : NhanvienList) {
                String email = nV.getEmail();
                arrayEmail.add(email);
            }
        } else {
            arrayEmail.add(txtEmailto.getText());
        }
        for (int i = 0; i < arrayEmail.size(); i++) {
            try {
                Properties p = new Properties();
                p.put("mail.smtp.auth", "true");
                p.put("mail.smtp.starttls.enable", "true");
                p.put("mail.smtp.host", "smtp.gmail.com");
                p.put("mail.smtp.port", "587");

                String accountName = txtEmail.getText();
                String accountPassword = txtPassword.getText();

                // Lấy tên đăng nhập và mật khẩu từ giao diện người dùng và sử dụng để xác thực.
                Session s = Session.getInstance(p,
                        new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(accountName, accountPassword);
                    }
                });
                String from = txtEmail.getText();
                String tos = arrayEmail.get(i).toString();
                String subject = txtSubject.getText();
                String body = txtMessage.getText();

                Message msg = new MimeMessage(s);
                msg.setFrom(new InternetAddress(from));
                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(tos));

                // bổ sung file đính kèm
                MimeBodyPart contentPart = new MimeBodyPart();
                contentPart.setContent(body, "text/html; charset=utf-8");

                msg.setSubject(subject);
                msg.setText(body);
                MimeMultipart mulTiPart = new MimeMultipart();
                if (duongDan != null && !duongDan.isEmpty()) {
                    MimeBodyPart filePart = new MimeBodyPart();
                    File file = new File(duongDan);
                    FileDataSource fds = new FileDataSource(file);  // FileDataSource là một lớp trong JavaMail API dùng để đọc dữ liệu từ một file. 
                    filePart.setDataHandler(new DataHandler(fds));
                    filePart.setFileName(file.getName());
                    mulTiPart.addBodyPart(filePart);
                }
                mulTiPart.addBodyPart(contentPart);

                msg.setContent(mulTiPart);

                Transport.send(msg);
                JOptionPane.showMessageDialog(null, "Gửi thành công");
            } catch (MessagingException e) {
                JOptionPane.showMessageDialog(null, "Gửi Không thành công");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radioNTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNTKActionPerformed
//        isMultipleRecipients = true;
        txtEmailto.setEditable(false);
    }//GEN-LAST:event_radioNTKActionPerformed

    private void radio1TKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1TKActionPerformed
//        isMultipleRecipients = false;
        txtEmailto.setEditable(true);
    }//GEN-LAST:event_radio1TKActionPerformed

    private void btnChonFDinhKem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFDinhKem1ActionPerformed
        JFileChooser f = new JFileChooser("D:");
        f.setDialogTitle("Mở File");
        int result = f.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fileAnh = f.getSelectedFile();
            duongDan = fileAnh.getAbsolutePath();
            txtDuongDan.setText(duongDan);
        } else {
            duongDan = null;
            txtDuongDan.setText("");
        }
    }//GEN-LAST:event_btnChonFDinhKem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonFDinhKem1;
    private javax.swing.JButton btnHuyChonF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio1TK;
    private javax.swing.JRadioButton radioNTK;
    private javax.swing.JTextField txtDuongDan;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailto;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
