/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.NhaCungCapDao;
import dao.NhanVienDao;
import dao.TaiKhoanDao;
import entity.NhaCungCap;
import entity.NhanVien;
import entity.TaiKhoan;
import java.awt.event.ItemEvent;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import url.RmiConfig;

/**
 *
 * @author dinhh
 */
public class GUI_TaiKhoan extends javax.swing.JPanel {

    private DefaultTableModel dataModel;
    //private ArrayList<NhanVien> dsNhanVien = daoNV.docTuBang();

    private static final String URL = RmiConfig.RMI_URL;
    private NhanVienDao nvDao;
    private NhaCungCapDao nccDao;
    private TaiKhoanDao tkDao;

    public GUI_TaiKhoan() throws java.rmi.RemoteException {

        try {
            nvDao = (NhanVienDao) Naming.lookup(URL + "NhanVien");
            nccDao = (NhaCungCapDao) Naming.lookup(URL + "NhaCungCap");
            tkDao = (TaiKhoanDao) Naming.lookup(URL + "TaiKhoan");
        } catch (RemoteException | MalformedURLException | NotBoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        initComponents();
        dataModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Nhân Viên", "Tên Nhân Viên", "Tên Tài Khoản", "Mật Khẩu", "Quyền Truy Cập"
                }
        );
        tblDSTaiKhoan.setModel(dataModel);
        //ConnectSQL.getInstance().connect();
        getDataMaNhanVien();
        updateComboBox();
        updateAccountTableData();
        txtTenNhanVien.setEditable(false);

    }

    private void updateComboBox() throws java.rmi.RemoteException {
        //NhanVienImpl ds = new NhanVienImpl();
        List<NhanVien> list = nvDao.docTuBang();
        cboMaNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(ItemEvent arg0) {
                if (arg0.getStateChange() == ItemEvent.SELECTED) {
                    String selectedMaNhanVien = cboMaNhanVien.getSelectedItem().toString();

                    NhanVien selectedNhanVien = null;
                    for (NhanVien nv : list) {
                        String maNV = nv.getMaNhanVien();
                        if (maNV.equals(selectedMaNhanVien)) {
                            selectedNhanVien = nv;
                            System.out.println(selectedNhanVien);
                            break;
                        }
                    }
                    if (selectedNhanVien != null) {
                        txtTenNhanVien.setText(selectedNhanVien.getTenNhanVien());
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblQuyenTruyCap = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtTenTaiKhoan = new javax.swing.JTextField();
        cboQuyenTruyCap = new javax.swing.JComboBox<>();
        lblChucNang = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        cboMaNhanVien = new javax.swing.JComboBox<>();
        lblQuanLyTaiKhoan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSTaiKhoan = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaNhanVien.setText("Mã Nhân Viên");

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenNhanVien.setText("Tên Nhân Viên");

        lblTenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenTaiKhoan.setText("Tên Tài Khoản");

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMatKhau.setText("Mật Khẩu");

        lblQuyenTruyCap.setText("Quyền Truy Cập");

        cboQuyenTruyCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên Bán Hàng", "Quản Lý" }));

        lblChucNang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChucNang.setText("Chức Năng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_refesh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_change.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblChucNang))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(45, 45, 45)
                                .addComponent(btnLamMoi)
                                .addGap(46, 46, 46)
                                .addComponent(btnXoa)
                                .addGap(42, 42, 42)
                                .addComponent(btnCapNhat)
                                .addGap(0, 469, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cboMaNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(312, 312, 312)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblMatKhau)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblTenNhanVien)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(225, 225, 225))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(cboQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTenTaiKhoan)
                                .addGap(67, 67, 67)
                                .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(lblTenNhanVien)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTaiKhoan)
                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatKhau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuyenTruyCap)
                    .addComponent(cboQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChucNang)
                    .addComponent(btnThem)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat))
                .addGap(37, 37, 37))
        );

        lblQuanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuanLyTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyTaiKhoan.setText("Quản Lý Tài Khoản");

        tblDSTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Tên Tài Khoản", "Mât Khẩu", "Quyền Truy Cập"
            }
        ));
        tblDSTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSTaiKhoan);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblQuanLyTaiKhoan)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearAccountTextFields();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblDSTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSTaiKhoanMouseClicked
        int row = tblDSTaiKhoan.getSelectedRow();
        if (row >= 0) {
            String maNhanVienStr = getValueAt(row, 0);
            String tenNhanVienStr = getValueAt(row, 1);
            String tenTaiKhoanStr = getValueAt(row, 2);
            String matKhauStr = getValueAt(row, 3);
            String quyenTruyCapStr = getValueAt(row, 4);

            cboMaNhanVien.setSelectedItem(maNhanVienStr);
            txtTenNhanVien.setText(tenNhanVienStr);
            txtTenTaiKhoan.setText(tenTaiKhoanStr);
            txtMatKhau.setText(matKhauStr);
            cboQuyenTruyCap.setSelectedItem(quyenTruyCapStr);
        }
    }//GEN-LAST:event_tblDSTaiKhoanMouseClicked
    private String getValueAt(int row, int column) {
        Object value = tblDSTaiKhoan.getValueAt(row, column);
        if (value != null) {
            return value.toString();
        }
        return "";
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            try {
                TaiKhoan account = revertAccountFormTextFile();
                if (tkDao.create(account)) {
                    //NhanVienImpl ds = new NhanVienImpl();
                    NhanVien nhanVien = nvDao.getNhanVienTheoMa(account.getMaNhanVien().getMaNhanVien());
                    Object[] rowData = {
                        account.getMaNhanVien().getMaNhanVien(),
                        nhanVien.getTenNhanVien(),
                        account.getTenTaiKhoan(),
                        account.getMatKhau(),
                        account.getQuyenTruyCap(),};
                    dataModel.addRow(rowData);
                }
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int row = tblDSTaiKhoan.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn tài khoản nào để xóa!");
            } else {
                int response = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    String supplierCode = tblDSTaiKhoan.getValueAt(row, 2).toString();
                    if (tkDao.delete(supplierCode)) {
                        DefaultTableModel dataModel = (DefaultTableModel) tblDSTaiKhoan.getModel();
                        dataModel.removeRow(row);
                        JOptionPane.showMessageDialog(null, "Xóa thành công tài khoản!");
                    }
                }
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        try {
            int row = tblDSTaiKhoan.getSelectedRow();
            if (row >= 0) {
                TaiKhoan acc = revertAccountFormTextFile();
                if (tkDao.update(acc)) {
                    //NhanVienImpl ds = new NhanVienImpl();
                    NhanVien nhanVien = nvDao.getNhanVienTheoMa(acc.getMaNhanVien().getMaNhanVien());
                    tblDSTaiKhoan.setValueAt(acc.getMaNhanVien().getMaNhanVien(), row, 0);
                    tblDSTaiKhoan.setValueAt(nhanVien.getTenNhanVien(), row, 1);
                    tblDSTaiKhoan.setValueAt(acc.getTenTaiKhoan(), row, 2);
                    tblDSTaiKhoan.setValueAt(acc.getMatKhau(), row, 3);
                    tblDSTaiKhoan.setValueAt(acc.getQuyenTruyCap(), row, 4);
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công tài khoản!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Chưa chọn tài khoản nào để sửa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed
    private void clearAccountTextFields() {
        txtTenNhanVien.setText("");
        cboMaNhanVien.setSelectedIndex(0);
        txtTenTaiKhoan.setText("");
        txtMatKhau.setText("");
        cboQuyenTruyCap.setSelectedIndex(0);

    }

    private void getDataMaNhanVien() throws RemoteException {
        for (int i = 0; i < nvDao.docTuBang().size(); i++) {
            cboMaNhanVien.addItem(String.valueOf(nvDao.docTuBang().get(i).getMaNhanVien()));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaNhanVien;
    private javax.swing.JComboBox<String> cboQuyenTruyCap;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChucNang;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQuanLyTaiKhoan;
    private javax.swing.JLabel lblQuyenTruyCap;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JTable tblDSTaiKhoan;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void updateAccountTableData() throws java.rmi.RemoteException {

        //TaiKhoanImpl account_DAO = new TaiKhoanImpl();
        List<TaiKhoan> accounts = tkDao.docTuBang();
        dataModel.setRowCount(0);

        for (TaiKhoan account : accounts) {
            //NhanVienImpl ds = new NhanVienImpl();
            NhanVien nhanVien = nvDao.getNhanVienTheoMa(account.getMaNhanVien().getMaNhanVien());
            String[] rowData = {
                account.getMaNhanVien().getMaNhanVien(),
                nhanVien.getTenNhanVien(),
                account.getTenTaiKhoan(),
                account.getMatKhau(),
                account.getQuyenTruyCap(),};
            dataModel.addRow(rowData);
        }
        tblDSTaiKhoan.setModel(dataModel);
    }

    private TaiKhoan revertAccountFormTextFile() {
        String maNhanVien = cboMaNhanVien.getSelectedItem().toString();
        String tenTaiKhoan = txtTenTaiKhoan.getText();
        String matKhau = txtMatKhau.getText();
        String quyenTruyCap = cboQuyenTruyCap.getSelectedItem().toString();
        if (tenTaiKhoan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chưa điền tên tài khoản", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (matKhau.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chưa điền mật khẩu", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return new TaiKhoan(new NhanVien(maNhanVien), tenTaiKhoan, matKhau, quyenTruyCap);
    }

}
