package gui;

import dao.NhaCungCapDao;
import entity.NhaCungCap;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import url.RmiConfig;

/**
 *
 * @author TriHieu
 */
public class GUI_TimKiemNhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form GUI_QuanLySP
     */
    //NhaCungCapImpl dSNCC = new NhaCungCapImpl();
    private static final String URL = RmiConfig.RMI_URL;
    private NhaCungCapDao nccDao ;
    private DefaultTableModel dataModel;

    public GUI_TimKiemNhaCungCap() throws java.rmi.RemoteException {
        try {
            nccDao = (NhaCungCapDao) Naming.lookup(URL + "NhaCungCap");
        } catch (RemoteException | MalformedURLException | NotBoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        initComponents();
        dataModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số Điện Thoại", "Địa Chỉ"
                }
        );
        tblDSNhaCungCap.setModel(dataModel);
        updateSupplierTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTimKiemNhaCungCap = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSNhaCungCap = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblMaNhaCungCap = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhaCungCap = new javax.swing.JTextField();
        lblTenNhaCungCap = new javax.swing.JLabel();
        txtMaNhaCungCap = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblSoDienThoai1 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        btnXuat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTimKiemNhaCungCap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTimKiemNhaCungCap.setText("Tìm Kiếm Nhà Cung Cấp");

        tblDSNhaCungCap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblDSNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số Điện Thoại", "Địa Chỉ"
            }
        ));
        jScrollPane2.setViewportView(tblDSNhaCungCap);

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaNhaCungCap.setText("Mã Nhà Cung Cấp");
        jPanel3.add(lblMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 133, -1, -1));
        jPanel3.add(txtTenNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 103, 178, -1));

        lblTenNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTenNhaCungCap.setText("Tên Nhà Cung Cấp");
        jPanel3.add(lblTenNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 101, -1, -1));

        txtMaNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMaNhaCungCapMouseExited(evt);
            }
        });
        jPanel3.add(txtMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 47, 175, -1));

        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_search.png"))); // NOI18N
        btnTim.setText("Tìm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel3.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 35, 135, -1));

        btnXoaRong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaRong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_change.png"))); // NOI18N
        btnXoaRong.setText("Xóa Rỗng");
        btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRongActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoaRong, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 143, 135, -1));

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 207, -1, -1));

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSoDienThoai.setText("Số Điện Thoại");
        jPanel3.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 149, -1, -1));
        jPanel3.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 191, 178, -1));

        lblSoDienThoai1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSoDienThoai1.setText("Địa Chỉ");
        jPanel3.add(lblSoDienThoai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 189, -1, -1));
        jPanel3.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 151, 178, -1));

        btnXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_excel.png"))); // NOI18N
        btnXuat.setText("Xuất Excel");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });
        jPanel3.add(btnXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 87, 135, -1));
        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(lblTimKiemNhaCungCap))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTimKiemNhaCungCap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaRongActionPerformed
        try {
            clearSupplierTextFields();
            updateSupplierTableData();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaRongActionPerformed

    private void txtMaNhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaNhaCungCapMouseExited


    }//GEN-LAST:event_txtMaNhaCungCapMouseExited

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("NhaCungCap");

                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < tblDSNhaCungCap.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(tblDSNhaCungCap.getColumnName(i));
                }
                for (int j = 0; j < tblDSNhaCungCap.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < tblDSNhaCungCap.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (tblDSNhaCungCap.getValueAt(j, k) != null) {
                            cell.setCellValue(tblDSNhaCungCap.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
                JOptionPane.showMessageDialog(null, "Xuất danh sách thành công!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXuatActionPerformed
    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException e) {
            System.out.println(e);
        }
    }
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        try {
            String maNhaCungCap = txtMaNhaCungCap.getText();
            String tenNhaCungCap = txtTenNhaCungCap.getText();
            String sdt = txtSoDienThoai.getText();
            String diaChi = txtDiaChi.getText();
            if (maNhaCungCap.isEmpty() && tenNhaCungCap.isEmpty() && sdt.isEmpty() && diaChi.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nhập ít nhất một thông tin để tìm kiếm", "Thông báo lỗi", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (!maNhaCungCap.isEmpty() && !maNhaCungCap.matches("^NCC\\d{3}$")) {
                JOptionPane.showMessageDialog(null, "Mã nhà cung cấp phải bắt đầu bằng NCC và có 3 kí tự số", "Thông báo lỗi", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (!sdt.isEmpty() && !sdt.matches("^[0-9]{10}$")) {
                JOptionPane.showMessageDialog(null, "Số điện thoại phải có 10 số", "Thông báo lỗi", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            //NhaCungCapImpl nhaCungCapDAO = new NhaCungCapImpl();
            List<NhaCungCap> danhSachNhaCungCap = null;

            danhSachNhaCungCap = nccDao.searchNhaCungCap(maNhaCungCap, tenNhaCungCap, sdt, diaChi);
//        try {
//            danhSachNhaCungCap = nhaCungCapDAO.searchNhaCungCap(maNhaCungCap, tenNhaCungCap, sdt, diaChi);
//        } catch (SQLException ex) {
//            Logger.getLogger(GUI_TimKiemNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
//        }
            if (danhSachNhaCungCap.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhà cung cấp thỏa mãn các điều kiện tìm kiếm");
            } else {
                dataModel.getDataVector().removeAllElements();

                for (NhaCungCap ncc : danhSachNhaCungCap) {
                    String[] rowData = {ncc.getMaNhaCungCap(), ncc.getTenNhaCungCap(), ncc.getSdt() + "", ncc.getDiaChi()};
                    dataModel.addRow(rowData);
                    JOptionPane.showMessageDialog(null, "Tìm thành công!");
                }

                tblDSNhaCungCap.setModel(dataModel);
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimActionPerformed
    private void clearSupplierTextFields() {
        txtMaNhaCungCap.setText("");
        txtTenNhaCungCap.setText("");
        txtSoDienThoai.setText("");
        txtDiaChi.setText("");

    }

    private void updateSupplierTableData() throws java.rmi.RemoteException {
        //NhaCungCapImpl supplierDAO = new NhaCungCapImpl();
        List<NhaCungCap> suppliers = nccDao.docTuBang(); // Implement this method in your DAO class to fetch suppliers.

        // Clear the existing data in the table (if needed).
        dataModel.setRowCount(0);

        for (NhaCungCap supplier : suppliers) {
            String[] rowData = {
                supplier.getMaNhaCungCap(),
                supplier.getTenNhaCungCap(),
                supplier.getSdt(),
                supplier.getDiaChi()
            };
            dataModel.addRow(rowData);
        }
        tblDSNhaCungCap.setModel(dataModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JButton btnXuat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMaNhaCungCap;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblSoDienThoai1;
    private javax.swing.JLabel lblTenNhaCungCap;
    private javax.swing.JLabel lblTimKiemNhaCungCap;
    private javax.swing.JTable tblDSNhaCungCap;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhaCungCap;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhaCungCap;
    // End of variables declaration//GEN-END:variables

}
