package gui;

import dao.HoaDon_DAO;
import dao.SanPham_DAO;
import dao.TaiKhoanDao;
import entity.HoaDon;
import entity.SanPham;
import entity.TaiKhoan;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import url.RmiConfig;

/**
 *
 * @author TriHieu
 */
public class GUI_LapHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form GUI_QuanLySP
     */
    public static DefaultTableModel dataModel;
    private static final String URL = RmiConfig.RMI_URL;
    private HoaDon_DAO hd;
    private TaiKhoanDao ds;
    public static SanPham_DAO daoSP;

    public GUI_LapHoaDon(String maNV) throws java.rmi.RemoteException {
        try {
            ds = (TaiKhoanDao) Naming.lookup(URL + "TaiKhoan");
            hd = (HoaDon_DAO) Naming.lookup(URL + "HoaDon");
            daoSP = (SanPham_DAO) Naming.lookup(URL + "SanPham");
        } catch (RemoteException | MalformedURLException | NotBoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        initComponents();

        String[] CTHoaDon = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"};
        dataModel = new DefaultTableModel(CTHoaDon, 0);
        tblChiTietHD.setModel(dataModel);
//        HoaDonImpl hd = new HoaDonImpl();
        List<HoaDon> list = hd.getListHoaDon();
        String ma = phatSinhMaHD(list);
        txtMaHD.setText(ma);
//        TaiKhoanImpl ds = new TaiKhoanImpl();
        TaiKhoan tk = ds.getTaiKhoanTheoTK(maNV);
        txtMaNV.setText(tk.getMaNhanVien().getMaNhanVien());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblMaHD = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        btnTaoHoaDon = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblLapHD = new javax.swing.JLabel();
        txtKhachHang = new javax.swing.JTextField();
        lblThongTinHD = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btnKH = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTietHD = new javax.swing.JTable();
        pnHinhAnh = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        lblLoaiSP = new javax.swing.JLabel();
        txtLoaiSP = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        txtTenSP = new javax.swing.JTextField();
        btnSanPham = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaHD.setText("Mã Hóa Đơn");

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaNV.setText("Mã Nhân Viên");

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblKhachHang.setText("Khách Hàng");

        txtMaHD.setEditable(false);

        btnTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaoHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnTaoHoaDon.setText("Tạo Hóa Đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLapHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLapHD.setText("Lập Hóa Đơn");

        txtKhachHang.setEditable(false);

        lblThongTinHD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblThongTinHD.setText("Thông Tin Hóa Dơn");

        txtMaNV.setEditable(false);

        btnKH.setText("...");
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });

        tblChiTietHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jScrollPane2.setViewportView(tblChiTietHD);

        pnHinhAnh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaSP.setText("Mã Sản Phẩm");

        lblTenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenSP.setText("Tên Sản Phẩm");

        txtMaSP.setEditable(false);
        txtMaSP.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblLoaiSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoaiSP.setText("Loại Sản Phẩm");

        txtLoaiSP.setEditable(false);

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong.setText("Số Lượng");

        lblDonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDonGia.setText("Đơn Giá");

        txtDonGia.setEditable(false);

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtTenSP.setEditable(false);

        btnSanPham.setText("...");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP)
                            .addComponent(lblLoaiSP)
                            .addComponent(lblTenSP)
                            .addComponent(lblSoLuong)
                            .addComponent(lblDonGia)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pnHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pnHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSP)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSanPham))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSP)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoaiSP)
                            .addComponent(txtLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoLuong)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonGia)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(587, Short.MAX_VALUE)
                .addComponent(lblLapHD)
                .addGap(524, 524, 524))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKhachHang))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblThongTinHD)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lblMaNV)
                                .addGap(39, 39, 39)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnKH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLapHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHD)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhachHang)
                    .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKH))
                .addGap(18, 18, 18)
                .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblThongTinHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 158, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 158, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            xuLyThemVaoTable();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        try {
            GUI_SelectSP slSP = new GUI_SelectSP();
            slSP.setVisible(true);

            if (slSP.sanPhamTimDuoc != null) {
                txtMaSP.setText(slSP.sanPhamTimDuoc.getMaSP());
                txtTenSP.setText(slSP.sanPhamTimDuoc.getTenSP());
                txtLoaiSP.setText(slSP.sanPhamTimDuoc.getLoaiSP().getMaLoai());
                txtDonGia.setText(slSP.sanPhamTimDuoc.getGiaBan() + "");
                //loadAnh(slSP.sanPhamTimDuoc.getHinhAnh());
//                SanPhamImpl ds = new SanPhamImpl();
                SanPham sp = daoSP.getSanPhamTheoMa(slSP.sanPhamTimDuoc.getMaSP());
                loadAnh("image/SanPham/" + sp.getHinhAnh());

                txtSoLuong.setText("");
                //System.out.println(slSP.sanPhamTimDuoc.getSoLuong());
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            xuLyXoa();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed

        GUI_SelectKH kh = new GUI_SelectKH();
        kh.setVisible(true);
        if (kh.khachHangTimDuoc != null) {
            txtKhachHang.setText(kh.khachHangTimDuoc.getMaKH() + " - " + kh.khachHangTimDuoc.getTenKH());
        }

    }//GEN-LAST:event_btnKHActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblChiTietHD.getRowCount();
            if (row > 0) {
                if (!txtKhachHang.getText().isEmpty()) {
                    xuLyXuatHoaDonBanHang();
                } else {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng cần tạo hóa đơn", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Thông Tin Hóa Đơn phải có ít nhất 1 sản phẩm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed
    File fileAnhSP;

    private ImageIcon getAnhSP(String src) {
        src = src.trim().equals("") ? "default.png" : src;
        //Xử lý ảnh
        BufferedImage img = null;
        File fileImg = new File(src);

        if (!fileImg.exists()) {
            src = "default.png";
            fileImg = new File("image/SanPham/" + src);
        }

        try {
            img = ImageIO.read(fileImg);
            fileAnhSP = new File(src);
        } catch (IOException e) {
            fileAnhSP = new File("imgs/anhthe/avatar.jpg");
        }

        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);
        }

        return null;
    }

    private void loadAnh(String anh) {
        pnHinhAnh.setIcon(getAnhSP(anh));
    }
    DecimalFormat dcf = new DecimalFormat("###,###");

    private void xuLyThemVaoTable() throws java.rmi.RemoteException {
        String ma = txtMaSP.getText();
        if (ma.trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String ten = txtTenSP.getText();
        String loai = txtLoaiSP.getText();
        if (txtSoLuong.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!txtSoLuong.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Số lượng phải là số dương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        String donGia = txtDonGia.getText();
//        SanPhamImpl ds = new SanPhamImpl();
        SanPham sp = daoSP.getSanPhamTheoMa(ma);

        int soLuongConLai = sp.getSoLuong();

        if (soLuong <= 0) {
            JOptionPane.showMessageDialog(null, "Số lượng phải lớn hơn 0", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (soLuongConLai <= 0) {
            JOptionPane.showMessageDialog(null, ten + " đã hết hàng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (soLuong > soLuongConLai) {
            JOptionPane.showMessageDialog(null, "Số lượng " + ten + " chỉ còn lại " + soLuongConLai, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        xoaRong();
        for (int i = 0; i < tblChiTietHD.getRowCount(); i++) {
            String maTbl = tblChiTietHD.getValueAt(i, 0).toString();
            if (maTbl.equals(ma)) {
                int soLuongAdd = Integer.parseInt(tblChiTietHD.getValueAt(i, 3) + "");
                soLuongAdd += soLuong;
                donGia = donGia.replace(",", "");
                double donGiaSP = Double.parseDouble(donGia);

                tblChiTietHD.setValueAt(soLuongAdd, i, 3);
                tblChiTietHD.setValueAt(dcf.format(soLuongAdd * donGiaSP), i, 5);

                // cập nhật lại số lượng trong db
                daoSP.capNhatSoLuongSP(ma, -soLuong);
                // spBUS.capNhatSoLuongSP(ma, -soLuong);

                return;
            }
        }
        donGia = donGia.replace(",", "");
        double donGiaSP = Double.parseDouble(donGia);
        Vector vec = new Vector();
        vec.add(ma);
        vec.add(ten);
        vec.add(loai);
        vec.add(soLuong);
        vec.add(donGiaSP);
        vec.add(dcf.format(soLuong * donGiaSP));
        daoSP.capNhatSoLuongSP(ma, -soLuong);

        dataModel.addRow(vec);
    }

    private void xuLyXoa() throws java.rmi.RemoteException {
        int row = tblChiTietHD.getSelectedRow();
        if (row > -1) {
            int option = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa " + tblChiTietHD.getValueAt(row, 1).toString() + " khỏi Thông Tin Hóa Đơn không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                String ma = (String) tblChiTietHD.getValueAt(row, 0);
                int soLuong = Integer.parseInt(tblChiTietHD.getValueAt(row, 3).toString());
//                SanPhamImpl ds = new SanPhamImpl();
                daoSP.capNhatSoLuongSP(ma, soLuong);
                dataModel.removeRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chọn sản phẩm trong Thông Tin Hóa Đơn để xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void xuLyXuatHoaDonBanHang() throws java.rmi.RemoteException {
        ArrayList<Vector> dsGioHang = new ArrayList<>();
        int row = tblChiTietHD.getRowCount();
        if (row == 0) {
            return;
        }
        double tongTien = 0;
        for (int i = 0; i < row; i++) {
            Vector vec = new Vector();
            vec.add(tblChiTietHD.getValueAt(i, 0));
            vec.add(tblChiTietHD.getValueAt(i, 1));
            vec.add(tblChiTietHD.getValueAt(i, 2));
            vec.add(tblChiTietHD.getValueAt(i, 3));
            vec.add(tblChiTietHD.getValueAt(i, 4));
            vec.add(tblChiTietHD.getValueAt(i, 5));
            tongTien += Double.parseDouble((tblChiTietHD.getValueAt(i, 5) + "").replace(",", ""));
            dsGioHang.add(vec);
        }
        GUI_XuatHoaDon xd = new GUI_XuatHoaDon(dsGioHang, tongTien, txtMaNV.getText(), txtKhachHang.getText(), txtMaHD.getText());
        xd.setVisible(true);
        if (xd.checkBanHang) {
            dataModel.setRowCount(0);
//            HoaDonImpl hd = new HoaDonImpl();
            List<HoaDon> list = hd.getListHoaDon();
            String ma = phatSinhMaHD(list);
            txtMaHD.setText(ma);
            txtKhachHang.setText("");
        }
    }

    public static void xuLyXoaKhiThoat(int row) throws java.rmi.RemoteException {

        if (row > -1) {
            String ma = (String) tblChiTietHD.getValueAt(row, 0);
            int soLuong = Integer.parseInt(tblChiTietHD.getValueAt(row, 3).toString());
//            SanPhamImpl ds = new SanPhamImpl();
            daoSP.capNhatSoLuongSP(ma, soLuong);
        }
    }

    public static void xuLyThoat() throws java.rmi.RemoteException {
        if (tblChiTietHD != null) {
            int row = tblChiTietHD.getRowCount();
            if (row > 0) {
                for (int i = 0; i < row; i++) {
                    xuLyXoaKhiThoat(i);
                }
            }
        }
    }

    private String phatSinhMaHD(List<HoaDon> hd) {
        int maxCode = 0;
        for (HoaDon hoaDon : hd) {
            String maHD = hoaDon.getMaHD();
            int code = Integer.parseInt(maHD.substring(2));
            if (code > maxCode) {
                maxCode = code;
            }
        }
        // Tạo mã khách hàng mới bằng cách tăng số lên 1 đơn vị
        maxCode++;
        if (maxCode < 1000) {
            String newCode = "HD" + String.format("%03d", maxCode);
            return newCode;
        } else if (maxCode < 10000) {
            String newCode = "HD" + String.format("%04d", maxCode);
            return newCode;
        } else {
            // Xử lý khi mã vượt quá 9999
            JOptionPane.showMessageDialog(null, "Mã số đã đạt tối đa, cần cập nhật thêm", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void xoaRong() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtLoaiSP.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
        loadAnh("image/SanPham/" + "default.png");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKH;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblLapHD;
    private javax.swing.JLabel lblLoaiSP;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThongTinHD;
    private javax.swing.JLabel pnHinhAnh;
    public static javax.swing.JTable tblChiTietHD;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtLoaiSP;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables

}
