package gui;

import dao.LoaiSanPham_DAO;
import dao.NhaCungCapDao;
import dao.SanPham_DAO;
import entity.LoaiSanPham;
import entity.NhaCungCap;
import entity.SanPham;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import url.RmiConfig;

/**
 *
 * @author TriHieu
 */
public class GUI_TimKiemSP extends javax.swing.JPanel {

    /**
     * Creates new form GUI_QuanLySP
     */
    //SanPhamImpl dsSP = new SanPhamImpl();
    private static final String URL = RmiConfig.RMI_URL;
    private SanPham_DAO spDao;
    private LoaiSanPham_DAO lspDao ;
    NhaCungCapDao nccDao ;
    DefaultTableModel dataModel;
    File fileAnhSP;

    public GUI_TimKiemSP() throws java.rmi.RemoteException {
        try {
             spDao = (SanPham_DAO) Naming.lookup(URL + "SanPham");
             lspDao = (LoaiSanPham_DAO) Naming.lookup(URL + "LoaiSanPham");
             nccDao = (NhaCungCapDao) Naming.lookup(URL + "NhaCungCap");
        } catch (RemoteException | MalformedURLException | NotBoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        initComponents();
        String[] sanPham = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá", "Mã Loại", "Mã Nhà Cung Cấp", "Hình Ảnh"};
        dataModel = new DefaultTableModel(sanPham, 0);
        tblSanPham.setModel(dataModel);
        //Connection.ConnectSQL.getInstance().connect();
        loadLoaiSP();
        loadNCC();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        lblLoai = new javax.swing.JLabel();
        cboNCC = new javax.swing.JComboBox<>();
        txtTen = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtSoLuongDen = new javax.swing.JTextField();
        lblSLDen = new javax.swing.JLabel();
        txtSoLuongTu = new javax.swing.JTextField();
        cboLoai = new javax.swing.JComboBox<>();
        lblNCC = new javax.swing.JLabel();
        lblSLTu = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblGiaTu = new javax.swing.JLabel();
        lblGiaDen = new javax.swing.JLabel();
        txtGiaTu = new javax.swing.JTextField();
        txtGiaDen = new javax.swing.JTextField();
        lblHinhAnh = new javax.swing.JLabel();
        lblMa1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        lblMa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMa.setText("Mã Sản Phẩm");

        lblLoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblLoai.setText("Loại Sản Phẩm");

        cboNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        lblTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTen.setText("Tên Sản Phẩm");

        lblSLDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSLDen.setText("Đến");

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));
        cboLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiActionPerformed(evt);
            }
        });

        lblNCC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNCC.setText("Nhà Cung Cấp");

        lblSLTu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSLTu.setText("Từ");

        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_search.png"))); // NOI18N
        btnTim.setText("Tìm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tìm Kiếm Sản Phẩm");

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSoLuong.setText("Tìm Kiếm Theo Khoảng Số Lượng");

        lblGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGia.setText("Tìm Kiếm Theo Khoảng Giá");

        lblGiaTu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGiaTu.setText("Từ");

        lblGiaDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGiaDen.setText("Đến");

        lblHinhAnh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMa1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMa1.setText("Hình Ảnh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(529, 529, 529))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoLuong)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSLTu)
                                    .addComponent(lblSLDen))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSoLuongDen, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuongTu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGiaTu)
                                    .addComponent(lblGiaDen))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblGia)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMa)
                            .addComponent(lblTen))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLoai)
                            .addComponent(lblNCC))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMa1)
                        .addGap(198, 198, 198))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSLDen)
                            .addComponent(txtSoLuongDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblMa1)
                                .addGap(18, 18, 18)
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMa)
                                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLoai)
                                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTen)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNCC)
                                    .addComponent(cboNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSoLuong)
                                    .addComponent(lblGia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoLuongTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSLTu)
                                    .addComponent(btnTim)
                                    .addComponent(lblGiaTu)
                                    .addComponent(txtGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGiaDen)
                                    .addComponent(txtGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(btnLamMoi)))
                        .addGap(29, 29, 29))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá", "Mã Loại", "Mã Nhà Cung Cấp", "Hình Ảnh"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        try {
            timKiemSanPham();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        try {
            xoaRong();
            dataModel.setRowCount(0);
            updateTable();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tblSanPham.getSelectedRow();
        loadAnh("image/SanPham/" + tblSanPham.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void cboLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiActionPerformed
    private void loadLoaiSP() throws java.rmi.RemoteException {
        //LoaiSanPhamImpl loai = new LoaiSanPhamImpl();
        List<LoaiSanPham> list = lspDao.docTuBang();
        for (LoaiSanPham loaiSP : list) {
            cboLoai.addItem(loaiSP.getMaLoai());
        }
    }

    private void loadNCC() throws java.rmi.RemoteException {
        //NhaCungCapImpl ncc = new NhaCungCapImpl();
        List<NhaCungCap> list = nccDao.docTuBang();
        for (NhaCungCap nhaCC : list) {
            cboNCC.addItem(nhaCC.getMaNhaCungCap());
        }
    }

    private void updateTable() throws java.rmi.RemoteException {
        //SanPhamImpl ds = new SanPhamImpl();
        List<SanPham> list = spDao.docTuBang();
        for (SanPham sp : list) {
            String[] rowData = {sp.getMaSP(), sp.getTenSP(), sp.getSoLuong() + "", sp.getGiaBan() + "", sp.getLoaiSP().getMaLoai(), sp.getNhaCungCap().getMaNhaCungCap() + "", sp.getHinhAnh()};
            dataModel.addRow(rowData);
        }
        tblSanPham.setModel(dataModel);
    }

    private void timKiemSanPham() throws RemoteException {
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        int indexLoai = cboLoai.getSelectedIndex();
        String loai = cboLoai.getSelectedItem().toString();
        int indexNCC = cboNCC.getSelectedIndex();
        String ncc = cboNCC.getSelectedItem().toString();
        String giaDau = txtGiaTu.getText();
        String giaCuoi = txtGiaDen.getText();
        String slDau = txtSoLuongTu.getText();
        String slCuoi = txtSoLuongDen.getText();

        double giaTu = -1;
        double giaDen = -1;
        int slTu = -1;
        int slDen = -1;

        if (ma.isEmpty() && ten.isEmpty() && giaDau.isEmpty() && giaCuoi.isEmpty() && slDau.isEmpty() && slCuoi.isEmpty() && indexNCC == 0 && indexLoai == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập hoặc chọn ít nhất 1 thông tin để tìm kiếm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!giaDau.isEmpty() && giaDau.matches("\\d+")) {
            giaTu = Double.parseDouble(giaDau);

        } else if (!giaDau.isEmpty() && !giaDau.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Giá phải là số dương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!giaCuoi.isEmpty() && giaCuoi.matches("\\d+")) {
            giaDen = Double.parseDouble(giaCuoi);

        } else if (!giaCuoi.isEmpty() && !giaCuoi.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Giá phải là số dương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!slDau.isEmpty() && slDau.matches("\\d+")) {
            slTu = Integer.parseInt(slDau);

        } else if (!slDau.isEmpty() && !slDau.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số dương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!slCuoi.isEmpty() && slCuoi.matches("\\d+")) {
            slDen = Integer.parseInt(slCuoi);

        } else if (!slCuoi.isEmpty() && !slCuoi.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số dương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (giaDen >= 0 && giaTu >= 0 && (giaTu > giaDen)) {
            JOptionPane.showMessageDialog(this, "Giá từ phải nhỏ hơn hoặc bằng giá đến", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (slDen >= 0 && slTu >= 0 && (slTu > slDen)) {
            JOptionPane.showMessageDialog(this, "Số lượng từ phải nhỏ hơn hoặc bằng số lượng đến", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (indexLoai == 0) {
            loai = "";
        }
        if (indexNCC == 0) {
            ncc = "";
        }
        //SanPhamImpl ds = new SanPhamImpl();
        List<SanPham> list = spDao.timKiemSanPham(ma, ten, loai, ncc, giaTu, giaDen, slTu, slDen);
        int sl = list.size();
        if (sl > 0) {
            dataModel.getDataVector().removeAllElements();
            for (SanPham sp : list) {
                String[] rowData = {sp.getMaSP(), sp.getTenSP(), sp.getSoLuong() + "", sp.getGiaBan() + "", sp.getLoaiSP().getMaLoai(), sp.getNhaCungCap().getMaNhaCungCap() + "", sp.getHinhAnh()};
                dataModel.addRow(rowData);
            }
            tblSanPham.setModel(dataModel);
        } else {
            dataModel.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm nào", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private ImageIcon getAnhSP(String src) {
        src = src.trim().equals("") ? "default.png" : src;
        //Xử lý ảnh
        BufferedImage img = null;
        File fileImg = new File(src);

        if (!fileImg.exists()) {
            src = "default.png";
            fileImg = new File("image/SanPham/" + src);
        }

        try {
            img = ImageIO.read(fileImg);
            fileAnhSP = new File(src);
        } catch (IOException e) {
            fileAnhSP = new File("imgs/anhthe/avatar.jpg");
        }

        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);
        }

        return null;
    }

    private void loadAnh(String anh) {
        lblHinhAnh.setIcon(getAnhSP(anh));
    }

    private void xoaRong() {
        txtMa.setText("");
        txtTen.setText("");
        txtSoLuongTu.setText("");
        txtSoLuongDen.setText("");
        txtGiaTu.setText("");
        txtGiaDen.setText("");
        loadAnh("");
        cboLoai.setSelectedIndex(0);
        cboNCC.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboNCC;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGiaDen;
    private javax.swing.JLabel lblGiaTu;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMa1;
    private javax.swing.JLabel lblNCC;
    private javax.swing.JLabel lblSLDen;
    private javax.swing.JLabel lblSLTu;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTen;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaDen;
    private javax.swing.JTextField txtGiaTu;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSoLuongDen;
    private javax.swing.JTextField txtSoLuongTu;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
