package gui;

import dao.ChiTietHoaDonDao;
import dao.HoaDon_DAO;
import dao.SanPham_DAO;
import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.SanPham;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import url.RmiConfig;

/**
 *
 * @author TriHieu
 */
public class GUI_TimKiemHD extends javax.swing.JPanel {

    /**
     * Creates new form GUI_QuanLySP
     */
    private static final String URL = RmiConfig.RMI_URL;
    //HoaDonmpl hd = new HoaDonImpl();
    private HoaDon_DAO hdDao ;
    private ChiTietHoaDonDao ctHDDao ;
    private DefaultTableModel dataModelHoaDon;
    private DefaultTableModel dataModelCTHoaDon;
    private DecimalFormat dcf = new DecimalFormat("###,###");
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    ;
    public GUI_TimKiemHD() throws java.rmi.RemoteException {
        try {
            hdDao = (HoaDon_DAO) Naming.lookup(URL + "HoaDon");
            ctHDDao = (ChiTietHoaDonDao) Naming.lookup(URL + "ChiTietHoaDon");
        }catch (RemoteException | MalformedURLException | NotBoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        initComponents();
        String[] TBLHoaDon = {"Mã Hóa Đơn", "Ngày Tạo", "Mã Khách Hàng", "Mã Nhân Viên", "Tổng Tiền"};
        dataModelHoaDon = new DefaultTableModel(TBLHoaDon, 0);
        tblHoaDon.setModel(dataModelHoaDon);

        String[] TBLCTHoaDon = {"Mã Hóa Đơn", "Mã Sản Phầm", "Số Lượng", "Đơn Giá", "Thành Tiền"};
        dataModelCTHoaDon = new DefaultTableModel(TBLCTHoaDon, 0);
        tblChiTietHoaDon.setModel(dataModelCTHoaDon);
       // Connection.ConnectSQL.getInstance().connect();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblMaHD = new javax.swing.JLabel();
        lblTuNgay = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        lblGiaTu = new javax.swing.JLabel();
        txtGiaTu = new javax.swing.JTextField();
        lblGiaDen = new javax.swing.JLabel();
        txtGiaDen = new javax.swing.JTextField();
        txtTuNgay = new javax.swing.JTextField();
        lblMaHD1 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblMaHD4 = new javax.swing.JLabel();
        lblNgayDen = new javax.swing.JLabel();
        txtNgayDen = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        lblMaHD2 = new javax.swing.JLabel();
        lblMaHD3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaHD.setText("Mã Hóa Đơn");

        lblTuNgay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTuNgay.setText("Từ Ngày");

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tìm Kiếm Hóa Đơn");

        lblMaKH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaKH.setText("Mã Khách Hàng");

        lblGiaTu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGiaTu.setText("Từ");

        lblGiaDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGiaDen.setText("Đến");

        lblMaHD1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaHD1.setText("Tìm Kiếm Theo Khoảng Tổng Tiền");

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaNV.setText("Mã Nhân Viên");

        lblMaHD4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaHD4.setText("Tìm Kiếm Theo Khoảng Ngày");

        lblNgayDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNgayDen.setText("Đến Ngày");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaHD)
                            .addComponent(lblTuNgay)
                            .addComponent(lblNgayDen))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMaHD4))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGiaTu)
                        .addGap(28, 28, 28)
                        .addComponent(txtGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(990, 990, 990))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblMaKH)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(lblMaNV)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblGiaDen)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(106, 106, 106)
                                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblMaHD1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHD)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKH)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHD1)
                    .addComponent(lblMaHD4))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTuNgay)
                    .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaTu)
                    .addComponent(txtGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayDen)
                    .addComponent(lblGiaDen)
                    .addComponent(txtGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Tạo", "Mã Khách Hàng", "Mã Nhân Viên", "Tổng Tiền"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Mã Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jScrollPane3.setViewportView(tblChiTietHoaDon);

        lblMaHD2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaHD2.setText("Hóa Đơn");

        lblMaHD3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaHD3.setText("Chi Tiết Hóa Đơn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(lblMaHD2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMaHD3)
                .addGap(286, 286, 286))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHD2)
                    .addComponent(lblMaHD3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        try {
            timKiemHoaDon();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        xoaRong();
        dataModelHoaDon.setRowCount(0);
        dataModelCTHoaDon.setRowCount(0);
        try {
            updateTable();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int row = tblHoaDon.getSelectedRow();
        String ma = tblHoaDon.getValueAt(row, 0).toString();
        try {
            tableChiTietHoaDon(ma);
        } catch (RemoteException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed
    private void timKiemHoaDon() throws java.rmi.RemoteException {
//        String ma= txtMaHD.getText();
//        HoaDonImpl hd = new HoaDonImpl();
//        hd.tinhTongTienTheoMaHoaDon(ma);
//        System.out.println(hd.tinhTongTienTheoMaHoaDon(ma));
        String maHD = txtMaHD.getText().toString();
        String maKH = txtMaKH.getText().toString();
        String maNV = txtMaNV.getText().toString();
        String ngayDau = txtTuNgay.getText().toString();
        String ngayCuoi = txtNgayDen.getText().toString();
        String tongDau = txtGiaTu.getText();
        String tongCuoi = txtGiaDen.getText();

        double tongTu = -1;
        double tongDen = -1;
        if (maHD.isEmpty() && maKH.isEmpty() && maNV.isEmpty() && ngayDau.isEmpty() && ngayCuoi.isEmpty() && tongDau.isEmpty() && tongCuoi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ít nhất 1 thông tin để tìm kiếm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!tongDau.isEmpty() && tongDau.matches("\\d+")) {
            tongTu = Double.parseDouble(tongDau);
            System.out.println(tongTu);
        } else if (!tongDau.isEmpty() && !tongDau.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Giá phải là số dương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!tongCuoi.isEmpty() && tongCuoi.matches("\\d+")) {
            tongDen = Double.parseDouble(tongCuoi);
            System.out.println(tongDen);
        } else if (!tongCuoi.isEmpty() && !tongCuoi.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Giá phải là số dương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (tongDen >= 0 && tongTu >= 0 && (tongTu > tongDen)) {
            JOptionPane.showMessageDialog(this, "Tổng từ phải nhỏ hơn hoặc bằng tổng đến", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!ngayDau.isEmpty() && ngayDau.matches("\\d{2}-\\d{2}-\\d{4}")) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            LocalDate ngayTao = LocalDate.parse(ngayDau, formatter);
            if (ngayTao.isAfter(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Ngày Từ không vượt quá hiện tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } else if (!ngayDau.isEmpty() && !ngayDau.matches("\\d{2}-\\d{2}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Ngày có định dạng dd-MM-yyyy", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!ngayCuoi.isEmpty() && !ngayCuoi.matches("\\d{2}-\\d{2}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Ngày có định dạng dd-MM-yyyy", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!ngayDau.isEmpty() && !ngayCuoi.isEmpty()) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            if (LocalDate.parse(ngayDau, formatter).isAfter(LocalDate.parse(ngayCuoi, formatter))) {
                JOptionPane.showMessageDialog(this, "Ngày Từ không vượt quá ngày Đến", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        //HoaDonImpl ds = new HoaDonImpl();
        List<HoaDon> list = hdDao.timKiemHoaDon(maHD, ngayDau, ngayCuoi, maKH, maNV, tongTu, tongDen);
        int sl = list.size();
        if (sl > 0) {
            dataModelHoaDon.getDataVector().removeAllElements();
            for (HoaDon hd : list) {
                //String ma= txtMaHD.getText();
                //HoaDonImpl hdon = new HoaDonImpl();
                double tongTien = hdDao.tinhTongTienTheoMaHoaDon(hd.getMaHD());
                String[] rowData = {hd.getMaHD(), dtf.format(hd.getNgayTao()), hd.getMaKh().getMaKH(), hd.getMaNV().getMaNhanVien(), dcf.format(tongTien)};
                dataModelHoaDon.addRow(rowData);
            }
            tblHoaDon.setModel(dataModelHoaDon);
        } else {
            dataModelHoaDon.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Không tìm thấy hóa đơn nào", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void updateTable() throws java.rmi.RemoteException {
       // HoaDonImpl hoaDon = new HoaDonImpl();
        List<HoaDon> list = hdDao.getListHoaDon();
        for (HoaDon hd : list) {
            //String ma= txtMaHD.getText();
            //HoaDonImpl hdon = new HoaDonImpl();
            double tongTien = hdDao.tinhTongTienTheoMaHoaDon(hd.getMaHD());
            String[] rowData = {hd.getMaHD(), dtf.format(hd.getNgayTao()), hd.getMaKh().getMaKH(), hd.getMaNV().getMaNhanVien(), dcf.format(tongTien)};
            dataModelHoaDon.addRow(rowData);
        }
        tblHoaDon.setModel(dataModelHoaDon);

    }

    private void tableChiTietHoaDon(String ma) throws java.rmi.RemoteException {
        //ChiTietHoaDonImpl hoaDon = new ChiTietHoaDonImpl();
        List<ChiTietHoaDon> list = ctHDDao.getListHoaDonTheoMaHD(ma);
        dataModelCTHoaDon.setRowCount(0);
        for (ChiTietHoaDon hd : list) {
            String[] rowData = {hd.getMaHD().getMaHD(), hd.getMaSP().getMaSP(), hd.getSoLuong() + "", dcf.format(hd.getDonGia()), dcf.format(hd.getSoLuong() * hd.getDonGia())};
            dataModelCTHoaDon.addRow(rowData);
        }
        tblChiTietHoaDon.setModel(dataModelCTHoaDon);

    }

    private void xoaRong() {
        txtMaHD.setText("");
        txtMaKH.setText("");
        txtMaNV.setText("");
        txtGiaDen.setText("");
        txtGiaTu.setText("");
        txtNgayDen.setText("");
        txtTuNgay.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGiaDen;
    private javax.swing.JLabel lblGiaTu;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaHD1;
    private javax.swing.JLabel lblMaHD2;
    private javax.swing.JLabel lblMaHD3;
    private javax.swing.JLabel lblMaHD4;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgayDen;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtGiaDen;
    private javax.swing.JTextField txtGiaTu;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtTuNgay;
    // End of variables declaration//GEN-END:variables
}
