
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

//import Connection.ConnectSQL;
import dao.NhaCungCapDao;
import dao.TaiKhoanDao;
import entity.NhaCungCap;
import entity.TaiKhoan;
import java.awt.Desktop;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import url.RmiConfig;

/**
 *
 * @author dinhh
 */
public class GUI_NhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form GUI_NhaCungCap
     */
//    NhaCungCapImpl dSNCC = new NhaCungCapImpl();
    private DefaultTableModel dataModel;
    NhaCungCapDao dSNCC;
    private static final String URL = RmiConfig.RMI_URL;

    public GUI_NhaCungCap() throws java.rmi.RemoteException {
        try {
            dSNCC = (NhaCungCapDao) Naming.lookup(URL + "NhaCungCap");
        } catch (RemoteException | MalformedURLException | NotBoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        initComponents();

//        NhaCungCapImpl supplierDAO = new NhaCungCapImpl();
        dataModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số Điện Thoại", "Địa Chỉ"
                }
        );
        tblDSNhaCungCap.setModel(dataModel);
//        ConnectSQL.getInstance().connect();
        updateSupplierTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMaNCC = new javax.swing.JLabel();
        lblTenNCC = new javax.swing.JLabel();
        lblSdtNCC = new javax.swing.JLabel();
        lblDiaChiNCC = new javax.swing.JLabel();
        lblChucNang = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        txtMaNCC = new javax.swing.JTextField();
        txtDiaChiNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtDienThoaiNCC = new javax.swing.JTextField();
        btnXuatExcel = new javax.swing.JButton();
        btnNhapExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSNhaCungCap = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhà Cung Cấp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaNCC.setText("Mã Nhà Cung Cấp");

        lblTenNCC.setText("Tên Nhà Cung Cấp");

        lblSdtNCC.setText("Số Điện Thoại");

        lblDiaChiNCC.setText("Địa Chỉ");

        lblChucNang.setText("Chức Năng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_refesh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_change.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_excel.png"))); // NOI18N
        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });

        btnNhapExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_excel.png"))); // NOI18N
        btnNhapExcel.setText("Nhập Excel");
        btnNhapExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaNCC)
                    .addComponent(lblSdtNCC)
                    .addComponent(lblChucNang))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(46, 46, 46)
                        .addComponent(btnLamMoi)
                        .addGap(48, 48, 48)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapNhat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDienThoaiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDiaChiNCC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTenNCC)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50)
                .addComponent(btnNhapExcel)
                .addGap(27, 27, 27)
                .addComponent(btnXuatExcel)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNCC)
                    .addComponent(lblTenNCC)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSdtNCC)
                    .addComponent(lblDiaChiNCC)
                    .addComponent(txtDienThoaiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChucNang)
                    .addComponent(btnThem)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnNhapExcel)
                    .addComponent(btnXuatExcel))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        tblDSNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số Điện Thoại", "Địa Chỉ"
            }
        ));
        tblDSNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSNhaCungCap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            try {
                NhaCungCap supplier = revertNCCFormTextFile();

                if (dSNCC.create(supplier)) {
                    Object[] rowData = {
                        supplier.getMaNhaCungCap(),
                        supplier.getTenNhaCungCap(),
                        supplier.getSdt(),
                        supplier.getDiaChi(),};
                    dataModel.addRow(rowData);
                    JOptionPane.showMessageDialog(null, "Thêm nhà cung cấp thành công!");
                }

            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearSupplierTextFields();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int row = tblDSNhaCungCap.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn nhà cung cấp nào để xóa!");
            } else {
                int response = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    String supplierCode = tblDSNhaCungCap.getValueAt(row, 0).toString();

                    if (dSNCC.delete(supplierCode)) {
                        DefaultTableModel dataModel = (DefaultTableModel) tblDSNhaCungCap.getModel();
                        dataModel.removeRow(row);
                        JOptionPane.showMessageDialog(null, "Xóa nhà cung cấp thành công!");
                    }
                }
            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDSNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSNhaCungCapMouseClicked
        int row = tblDSNhaCungCap.getSelectedRow();
        txtMaNCC.setText(tblDSNhaCungCap.getValueAt(row, 0).toString());
        txtTenNCC.setText(tblDSNhaCungCap.getValueAt(row, 1).toString());
        txtDienThoaiNCC.setText(tblDSNhaCungCap.getValueAt(row, 2).toString());
        txtDiaChiNCC.setText(tblDSNhaCungCap.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblDSNhaCungCapMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int row = tblDSNhaCungCap.getSelectedRow();
        if (row >= 0) {
            NhaCungCap supplier = revertNCCFormTextFile();
            try {
                if (dSNCC.update(supplier)) {
                    tblDSNhaCungCap.setValueAt(supplier.getMaNhaCungCap(), row, 0);
                    tblDSNhaCungCap.setValueAt(supplier.getTenNhaCungCap(), row, 1);
                    tblDSNhaCungCap.setValueAt(supplier.getSdt(), row, 2);
                    tblDSNhaCungCap.setValueAt(supplier.getDiaChi(), row, 3);
                    JOptionPane.showMessageDialog(null, "Cập nhật thông tin nhà cung cấp thành công");
                }
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn nhà cung cấp nào để chỉnh sửa.");
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed


    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        try {
            JFileChooser jFileChooser = new JFileChooser("./excel");
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("NhaCungCap");

                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < tblDSNhaCungCap.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(tblDSNhaCungCap.getColumnName(i));
                }
                for (int j = 0; j < tblDSNhaCungCap.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < tblDSNhaCungCap.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (tblDSNhaCungCap.getValueAt(j, k) != null) {
                            cell.setCellValue(tblDSNhaCungCap.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                JOptionPane.showMessageDialog(null, "Xuất file Excel thành công!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void btnNhapExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapExcelActionPerformed
        File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelJTableImport = null;
        ArrayList<NhaCungCap> listAccExcel = new ArrayList<NhaCungCap>();
        JFileChooser jf = new JFileChooser("./excel");
        int result = jf.showOpenDialog(null);
        jf.setDialogTitle("Open file");
        Workbook workbook = null;

        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                excelFile = jf.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelJTableImport = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelJTableImport.getSheetAt(0);

                for (int row = 1; row <= excelSheet.getLastRowNum(); row++) {
                    XSSFRow excelRow = excelSheet.getRow(row);
//                    String maNhaCungCap = phatSinhMaNhaCungCap();
                    String maNhaCungCap = excelRow.getCell(0).getStringCellValue();
                    String tenNhaCungCap = excelRow.getCell(1).getStringCellValue();
                    String sdt = excelRow.getCell(2).getStringCellValue();
                    String diaChi = excelRow.getCell(3).getStringCellValue();
                    NhaCungCap acc = new NhaCungCap(maNhaCungCap, tenNhaCungCap, sdt, diaChi);
                    listAccExcel.add(acc);
                }

//                NhaCungCapImpl dao = new NhaCungCapImpl();
                int successCount = 0;

                for (NhaCungCap nhaCungCap : listAccExcel) {
                    boolean isSuccess = dSNCC.create(nhaCungCap);
                    if (!isSuccess) {
                        JOptionPane.showMessageDialog(null, "Thêm dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    } else {
                        successCount++;
                    }
                }

                if (successCount > 0) {
                    JOptionPane.showMessageDialog(null, "Thêm thành công !");
                }

                updateSupplierTableData();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnNhapExcelActionPerformed
//    private String phatSinhMaNhaCungCap() {
//        NhaCungCapImpl dao = new NhaCungCapImpl();
//        int soLuongNhaCungCap = dao.tinhSoLuong();
//
//        int soTiepTheo = soLuongNhaCungCap + 1;
//        String maMoi = "NCC" + String.format("%03d", soTiepTheo);
//
//        return maMoi;
//    }

    private void updateSupplierTableData() throws java.rmi.RemoteException {
//        NhaCungCapImpl supplierDAO = new NhaCungCapImpl();
        List<NhaCungCap> suppliers = dSNCC.docTuBang();

        dataModel.setRowCount(0);

        for (NhaCungCap supplier : suppliers) {
            String[] rowData = {
                supplier.getMaNhaCungCap(),
                supplier.getTenNhaCungCap(),
                supplier.getSdt(),
                supplier.getDiaChi()
            };
            dataModel.addRow(rowData);
        }
        tblDSNhaCungCap.setModel(dataModel);
    }

    private void clearSupplierTextFields() {
        txtMaNCC.setText("");
        txtTenNCC.setText("");
        txtDienThoaiNCC.setText("");
        txtDiaChiNCC.setText("");
    }

    private NhaCungCap revertNCCFormTextFile() {
        String maNCC = txtMaNCC.getText();
        String tenNCC = txtTenNCC.getText();
        String sdt = txtDienThoaiNCC.getText().toString();
        String diaChi = txtDiaChiNCC.getText();
        if (maNCC.isEmpty() && tenNCC.isEmpty() && sdt.isEmpty() && diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin nào để thêm nhà cung cấp", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (!txtMaNCC.getText().matches("^NCC\\d{3}$")) {
            JOptionPane.showMessageDialog(null, "Mã nhà cung cấp phải bắt đầu bằng NCC và 3 kí tự số", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (tenNCC.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên nhà cung cấp không được để trống", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!sdt.matches("^[0-9]{10}$")) {
            JOptionPane.showMessageDialog(null, "Số điện thoại phải có 10 số", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return new NhaCungCap(maNCC, tenNCC, sdt, diaChi);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNhapExcel;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChucNang;
    private javax.swing.JLabel lblDiaChiNCC;
    private javax.swing.JLabel lblMaNCC;
    private javax.swing.JLabel lblSdtNCC;
    private javax.swing.JLabel lblTenNCC;
    private javax.swing.JTable tblDSNhaCungCap;
    private javax.swing.JTextField txtDiaChiNCC;
    private javax.swing.JTextField txtDienThoaiNCC;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
